/* Generated By:JavaCC: Do not edit this line. DrawGrammarConstants.java */
package org.caferrerb.drawer.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DrawGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGN = 5;
  /** RegularExpression Id. */
  int PAR_OPEN = 6;
  /** RegularExpression Id. */
  int PAR_CLOSE = 7;
  /** RegularExpression Id. */
  int PARAM_SEP = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int POINT = 10;
  /** RegularExpression Id. */
  int RECTANGLE = 11;
  /** RegularExpression Id. */
  int CIRCLE = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<NUMBER>",
    "\"point\"",
    "\"rectangle\"",
    "\"circle\"",
    "<IDENTIFIER>",
  };

}
